### ISSUE TITLE
Webmail Error

### ISSUE THREAD

**Issue by bardie** [xme/dockers#13]
How do i fix the following issue. I have tried writing the code but still get the same code.

[INFO]: Connected to IMAP server.
[INFO]: 3 unread messages to process
Traceback (most recent call last):
  File "/usr/lib/python3.5/imaplib.py", line 1003, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib/python3.5/imaplib.py", line 1123, in _get_tagged_response
    self._get_response()
  File "/usr/lib/python3.5/imaplib.py", line 1086, in _get_response
    dat = self._get_line()
  File "/usr/lib/python3.5/imaplib.py", line 1135, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./imap2thehive.py", line 533, in <module>
    main()
  File "./imap2thehive.py", line 529, in main
    readMail(mailConnect())
  File "./imap2thehive.py", line 405, in readMail
    typ, dat = mbox.fetch(num, '(RFC822)')
  File "/usr/lib/python3.5/imaplib.py", line 518, in fetch
    typ, dat = self._simple_command(name, message_set, message_parts)
  File "/usr/lib/python3.5/imaplib.py", line 1180, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.5/imaplib.py", line 1005, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.abort: command: FETCH => socket error: EOF

**Comment by xme** [comment]
Strange, does it fail on a specific message/content?
I googled for this error and other tools have the same issue from time to time. I don't know how to fix this...

**Comment by bardie** [comment]
Based on the RFC822 documentation the alternative to RFC822 ID BODY[]. So for webmail instead of:

typ, dat = mbox.fetch(num, '(RFC822)')

use

typ, dat = mbox.fetch(num, '(BODY[])')
