### ISSUE TITLE
AttributeError: 'module' object has no attribute 'message_from_bytes'

### ISSUE THREAD

**Issue by dbsmsc** [xme/dockers#25]
I am getting this error:
essage_from_bytes(message)
AttributeError: 'module' object has no attribute 'message_from_bytes'

Any pointers?

Thank you.

Full:
[WARNING]: Both case template and tasks are defined. Template (thehive_template) will be used.
[INFO]: Processing REDACTED:993/Inbox
[INFO]: Connected to IMAP server.
[INFO]: 1 unread messages to process
Traceback (most recent call last):
  File "imap2thehive.py", line 548, in <module>
    main()
  File "imap2thehive.py", line 544, in main
    readMail(mailConnect())
  File "imap2thehive.py", line 417, in readMail
    if submitTheHive(message) == True:
  File "imap2thehive.py", line 195, in submitTheHive
    msg = email.message_from_bytes(message)
AttributeError: 'module' object has no attribute 'message_from_bytes'

**Comment by dbsmsc** [comment]
Resolved: Not using Python 3.
